*&---------------------------------------------------------------------*
*&  Include           ZMM_MALZEME_YARAT_GENEL_TOP
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF BLOCK blk1 WITH FRAME TITLE TEXT-t01.
  PARAMETERS: r_yp RADIOBUTTON GROUP r1 DEFAULT 'X'.
  PARAMETERS: r_ma  RADIOBUTTON GROUP r1 .
SELECTION-SCREEN END OF BLOCK blk1.

SELECTION-SCREEN BEGIN OF BLOCK blk2 WITH FRAME TITLE TEXT-t02.
  PARAMETERS: p_file LIKE rlgrap-filename.
SELECTION-SCREEN END OF BLOCK blk2.

DATA:   BDCDATA LIKE BDCDATA    OCCURS 0 WITH HEADER LINE.
DATA:   MESSTAB LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE.

DATA: BEGIN OF gt_excel OCCURS 0,
  MATNR(018),
  MBRSH(001),
  MTART(004),
  WERKS(004),
  LGORT(004),
  VKORG(004),
  VTWEG(002),
  MAKTX(040),
  MEINS(003),
  MATKL(009),
  EXTWG(018),
  BISMT(018),
  SPART(002),
  PRDHA(018),
  MTPOS_MARA(004),
  BRGEW(017),
  GEWEI(003),
  NTGEW(017),
  VOLUM(017),
  VOLEH(003),
  DWERK(004),
  SKTOF(001),
  TAXKM_01(001),
  TAXKM_02(001),
  TAXKM_03(001),
  TAXKM_04(001),
  TAXKM_05(001),
  VERSG(001),
  KONDM(002),
  KTGRM(002),
  MTPOS(004),
  MTVFP(002),
  TRAGR(004),
  LADGR(004),
  PRCTR(010),
  EKGRP(003),
  LGPBE(010),
  RAUBE(002),
  BKLAS(004),
  MLAST(001),
  PEINH(006),
  VPRSV(001),
  STAWN(017),
  BWTTY TYPE BWTTY_D,
  XCHPF TYPE XCHPF,
  STPRS(015),
" buradan sonrası
  QKLAS(004),
  BWKEY(004),
  BWTAR_D(010),
END OF gt_excel.

data: record LIKE LINE OF gt_excel.

DATA: HEADDATA  LIKE  BAPIMATHEAD,
      CLIENTDATA  LIKE  BAPI_MARA,
      CLIENTDATAX LIKE  BAPI_MARAX,
      PLANTDATA LIKE  BAPI_MARC,
      PLANTDATAX  LIKE  BAPI_MARCX,
      VALUATIONDATA LIKE  BAPI_MBEW,
      VALUATIONDATAX  LIKE  BAPI_MBEWX,
      SALESDATA LIKE  BAPI_MVKE,
      SALESDATAX  LIKE  BAPI_MVKEX,
      STORAGELOCATIONDATA   LIKE  BAPI_MARD,
      STORAGELOCATIONDATAX  LIKE  BAPI_MARDX,
      TAXCLASSIFICATIONS  LIKE  BAPI_MLAN OCCURS 0 WITH HEADER LINE ,
      tb_MATERIALDESCRIPTION LIKE BAPI_MAKT OCCURS 0 WITH HEADER LINE,
      tb_BATCHATTRIBUTES LIKE BAPIBATCHATT OCCURS 0 WITH HEADER LINE,
      UNITSOFMEASURE  LIKE  BAPI_MARM OCCURS 0 WITH HEADER LINE,
      UNITSOFMEASUREX LIKE  BAPI_MARMX OCCURS 0 WITH HEADER LINE,
      RETURNMESSAGES  LIKE  BAPI_MATRETURN2 OCCURS 0 WITH HEADER LINE,
      tb_return LIKE BAPIRET2.
*      TB_CLASS LIKE TABLE OF BAPIRET2 WITH HEADER LINE,
*      BAPI1003_ALLOC_VALUES_NUM   LIKE TABLE OF BAPI1003_ALLOC_VALUES_NUM  WITH HEADER LINE,
*      BAPI1003_ALLOC_VALUES_CHAR  LIKE TABLE OF BAPI1003_ALLOC_VALUES_CHAR WITH HEADER LINE,
*      BAPI1003_ALLOC_VALUES_CURR  LIKE TABLE OF BAPI1003_ALLOC_VALUES_CURR WITH HEADER LINE.
