************************************************************************
*        Entries aus RSNAST00                                          *
************************************************************************

  INCLUDE FM06PE01_ENTRY_NEU .  " ENTRY_NEU

  INCLUDE FM06PE01_ENTRY_AEND .  " ENTRY_AEND

  INCLUDE FM06PE01_ENTRY_AUFB .  " ENTRY_AUFB

  INCLUDE FM06PE01_ENTRY_MAHN .  " ENTRY_MAHN

  INCLUDE FM06PE01_ENTRY_ABSA .  " ENTRY_ABSA

  INCLUDE FM06PE01_ENTRY_LPHE_OLD .  " ENTRY_LPHE_OLD

  INCLUDE FM06PE01_ENTRY_LPHE .  " ENTRY_LPHE

  INCLUDE FM06PE01_ENTRY_LP_LAB .  " ENTRY_LP_LAB

  INCLUDE FM06PE01_ENTRY_LP_FAB .  " ENTRY_LP_FAB


  INCLUDE FM06PE01_ENTRY_LPET .  " ENTRY_LPET
  INCLUDE FM06PE01_ENTRY_LPE2 .  " ENTRY_LPE2

  INCLUDE FM06PE01_ENTRY_LPFZ .  " ENTRY_LPFZ

  INCLUDE FM06PE01_ENTRY_LPF2 .  " ENTRY_LPF2

  INCLUDE FM06PE01_ENTRY_LPMA .  " ENTRY_LPMA

  INCLUDE FM06PE01_ENTRY_LPMF .  " ENTRY_LPMF

  INCLUDE FM06PE01_ENTRY_LPJE .  " ENTRY_LPJE
  INCLUDE FM06PE01_VERARBEITE_LP_LAB_FAB .  " VERARBEITE_LP_LAB_FAB
