************************************************************************
*        Routinen für Dienstleistungen                                 *
************************************************************************

  INCLUDE FM06PF04_SELECT_SERVICES .  " SELECT_SERVICES

  INCLUDE FM06PF04_PRINT_GLIEDERUNG .  " PRINT_GLIEDERUNG

  INCLUDE FM06PF04_PRINT_SRVPOS .  " PRINT_SRVPOS

  INCLUDE FM06PF04_TEXTE .  " TEXTE

  INCLUDE FM06PF04_KONDITIONEN .  " KONDITIONEN


  INCLUDE FM06PF04_ZIELWERT .  " ZIELWERT

  INCLUDE FM06PF04_PRINT_ABRUFDATEN .  " PRINT_ABRUFDATEN
  INCLUDE FM06PF04_PRINT_TIME .  " PRINT_TIME
  INCLUDE FM06PF04_PRINT_FORMEL .  " PRINT_FORMEL


  INCLUDE FM06PF04_BLOCK_TEXT_LEISTUNG .  " BLOCK_TEXT_LEISTUNG

  INCLUDE FM06PF04_SELECT_BLOCK_TEXT .  " SELECT_BLOCK_TEXT
